server:
  port: 9191
  address: localhost
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/departments/**
          