server:
  port: 9296
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pablozoani/config-server
          clone-on-start: true
          password: ${GITHUB_PASSWORD:default}
          username: pablozoani@hotmail.com

